#!/usr/bin/env tsx
/**
 * Regenerate the import-ae bench: run the real CLI on every fixture, then
 * write the Remotion entry that pairs each generated composition with
 * `@remotion/lottie` playback of the same JSON.
 *
 *   pnpm --filter remotion-ui build
 *   cd apps/web && npx tsx showcase/import-ae-bench/generate.mts
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const cli = path.resolve(here, "../../../../packages/remotion-ui/dist/index.js");
const fixturesDir = path.join(here, "fixtures");
const generatedDir = path.join(here, "generated");

/** Fixtures that use features import-ae does not carry; generated past them. */
const SKIP_UNSUPPORTED = new Set(["android-wave"]);

const pascal = (slug: string) =>
  slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");

const slugs = fs
  .readdirSync(fixturesDir)
  .filter((f) => f.endsWith(".json"))
  .map((f) => f.replace(/\.json$/, ""))
  .sort();

fs.rmSync(generatedDir, { recursive: true, force: true });
const entries: { slug: string; component: string; meta: Record<string, number> }[] = [];

for (const slug of slugs) {
  const component = `${pascal(slug)}Import`;
  const args = [
    cli,
    "import-ae",
    path.join(fixturesDir, `${slug}.json`),
    "--out",
    path.join(generatedDir, slug),
    "--name",
    component,
    "--no-register",
    "--no-install",
    "--json",
    ...(SKIP_UNSUPPORTED.has(slug) ? ["--skip-unsupported"] : []),
  ];
  const output = execFileSync("node", args, { encoding: "utf8" });
  const result = JSON.parse(output.trim().split("\n").pop() ?? "{}");
  if (!result.ok) throw new Error(`${slug}: ${output}`);
  const unsupported = result.issues.filter((i: { level: string }) => i.level === "unsupported").length;
  console.log(`${slug}: ${result.files.length} file(s), ${unsupported} unsupported, ${result.composition.durationInFrames} frames`);
  entries.push({ slug, component, meta: result.composition });
}

const lines = [
  "// Generated by generate.mts — do not edit.",
  ...entries.map((e) => `import ${e.component.replace(/Import$/, "Json")} from "../fixtures/${e.slug}.json";`),
  ...entries.map((e) => `import { ${e.component} } from "../generated/${e.slug}";`),
  "",
  "export const FIXTURES = [",
  ...entries.map(
    (e) =>
      `  { slug: ${JSON.stringify(e.slug)}, json: ${e.component.replace(/Import$/, "Json")}, Generated: ${e.component}, ` +
      `fps: ${e.meta.fps}, width: ${e.meta.width}, height: ${e.meta.height}, durationInFrames: ${e.meta.durationInFrames} },`,
  ),
  "] as const;",
  "",
];
fs.writeFileSync(path.join(here, "src", "fixtures.gen.ts"), lines.join("\n"));
console.log(`wrote src/fixtures.gen.ts (${entries.length} fixtures)`);
