import type { Caption } from "@remotion/captions";
import { staticFile } from "remotion";
import { BRAND_MARK_SVG } from "./brand-mark-svg";

/**
 * Local 8-second loop generated by `scripts/generate-demo-audio.mts`.
 *
 * The previous remote source was a steady tone, so every audio-reactive preview
 * rendered a frozen shape. This one has a beat and a chord change per bar, which
 * is what makes the spectrum and waveform previews actually move.
 * `useWindowedAudioData()` only accepts `.wav`, so it stays uncompressed.
 */
export const DEMO_AUDIO_SRC = staticFile("media/demo-loop.wav");

/** Curated demo palette — see skills/remotion-ui/rules/component-polish.md */
export const DEMO_PALETTE = {
  phosphor: "#e8b86d",
  amber: "#f59e0b",
  teal: "#2dd4bf",
  rose: "#f472b6",
  bg: "#080810",
  bgRaised: "#0c0c14",
  text: "#fafafa",
  muted: "#71717a",
} as const;

/** Docs preview backdrop — matches caption-scene / audiogram-scene plate */
export const SCENE_PREVIEW_GRADIENT =
  `radial-gradient(circle at 18% 18%, rgba(232,184,109,0.14) 0%, transparent 46%), radial-gradient(circle at 82% 64%, rgba(45,212,191,0.10) 0%, transparent 52%), linear-gradient(to bottom, #050510 0%, ${DEMO_PALETTE.bg} 100%)`;

/** Aspect presets for docs preview QA */
export const PREVIEW_LANDSCAPE = { width: 960, height: 540 } as const;
export const PREVIEW_PORTRAIT = { width: 1080, height: 1920 } as const;
export const PREVIEW_HD = { width: 1920, height: 1080 } as const;

/** Story-specific copy deck — avoid tagline reuse across previews */
export const DEMO_COPY = {
  productLaunch: {
    title: "Frame registry",
    subtitle: "Install compositions as source you own",
    featureTitle: "Three layers in your repo",
    featureItems: [
      "Motion primitives you can edit",
      "Scenes for hooks, charts, and captions",
      "Compositions that wire the full story",
    ],
  },
  creatorHook: {
    eyebrow: "Creator insight",
    headline: "Make the first second count",
    subtitle: "Hook viewers before they scroll",
  },
  creatorComment: {
    author: "Alex Chen",
    handle: "@alexchen",
    body: "Can you break down how you built that transition?",
  },
  dataStory: {
    title: "Quarterly reach by channel",
    subtitle: "Short-form climbed while long-form held attention",
    chartTitle: "Views by format",
    metricsTitle: "Signals that mattered",
    timelineTitle: "How we read the quarter",
    insightEyebrow: "Takeaway",
    ctaTitle: "Turn your data into motion",
    statValue: 3,
    statLabel: "Runtime dependencies",
    statSuffix: "",
  },
  podcast: {
    title: "Ship faster with source",
    subtitle: "Edit every frame in your repo",
  },
  tutorial: {
    calloutTitle: "Wire the composition",
    calloutSubtitle: "Drop scenes into TransitionSeries",
  },
  quote: {
    text: "The best motion is code you can read and change.",
    attribution: "Remotion team",
  },
  endCard: {
    ctaLabel: "Browse components",
    ctaUrl: "remotionui.com/docs/components",
  },
} as const;

const svgData = (svg: string) =>
  `data:image/svg+xml,${encodeURIComponent(svg)}`;

export const DEMO_MEDIA_SRC = svgData(`
<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720" viewBox="0 0 1280 720">
  <defs>
    <linearGradient id="g" x1="0" x2="1" y1="0" y2="1">
      <stop stop-color="#111827"/>
      <stop offset="1" stop-color="#1a1510"/>
    </linearGradient>
  </defs>
  <rect width="1280" height="720" fill="url(#g)"/>
  <circle cx="1030" cy="146" r="190" fill="${DEMO_PALETTE.phosphor}" opacity=".18"/>
  <rect x="104" y="96" width="650" height="430" rx="42" fill="#f8fafc" opacity=".12"/>
  <rect x="154" y="154" width="450" height="38" rx="19" fill="#f8fafc" opacity=".78"/>
  <rect x="154" y="224" width="312" height="28" rx="14" fill="${DEMO_PALETTE.amber}" opacity=".85"/>
  <rect x="154" y="306" width="500" height="112" rx="28" fill="#020617" opacity=".42"/>
  <rect x="804" y="342" width="300" height="118" rx="34" fill="#f8fafc" opacity=".14"/>
  <text x="112" y="610" font-family="Arial,sans-serif" font-size="60" font-weight="700" fill="#f8fafc">Launch dashboard</text>
  <text x="114" y="658" font-family="Arial,sans-serif" font-size="28" fill="${DEMO_PALETTE.phosphor}">Feature story, KPI, and product frame</text>
</svg>`);

/**
 * The same product still without the baked headline.
 *
 * `DEMO_MEDIA_SRC` carries its own copy in the lower-left band — which is
 * exactly where a scene puts its label chips, its callout card and its lower
 * third. Every scene that overlays copy on footage covered that headline and
 * read as a clipping bug. Scenes that supply their own copy use this one;
 * scenes where the still *is* the subject keep the titled version.
 */
export const DEMO_MEDIA_PLAIN_SRC = svgData(`
<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720" viewBox="0 0 1280 720">
  <defs>
    <linearGradient id="g" x1="0" x2="1" y1="0" y2="1">
      <stop stop-color="#111827"/>
      <stop offset="1" stop-color="#1a1510"/>
    </linearGradient>
  </defs>
  <rect width="1280" height="720" fill="url(#g)"/>
  <circle cx="1030" cy="146" r="190" fill="${DEMO_PALETTE.phosphor}" opacity=".18"/>
  <rect x="104" y="96" width="650" height="430" rx="42" fill="#f8fafc" opacity=".12"/>
  <rect x="154" y="154" width="450" height="38" rx="19" fill="#f8fafc" opacity=".78"/>
  <rect x="154" y="224" width="312" height="28" rx="14" fill="${DEMO_PALETTE.amber}" opacity=".85"/>
  <rect x="154" y="306" width="500" height="112" rx="28" fill="#020617" opacity=".42"/>
  <rect x="804" y="342" width="300" height="118" rx="34" fill="#f8fafc" opacity=".14"/>
  <rect x="154" y="580" width="380" height="24" rx="12" fill="#f8fafc" opacity=".22"/>
  <rect x="154" y="628" width="240" height="18" rx="9" fill="#f8fafc" opacity=".12"/>
</svg>`);

/**
 * A picture, not a UI capture.
 *
 * Every other still in this file is a product card built out of grey bars — the
 * shape of a loading skeleton. Any preview whose subject *is* the image
 * (`image-expand`, ken-burns style frames) reads as an unfinished render when it
 * is handed one of those. This is a scene: sky, sun, ridges, water.
 */
export const DEMO_PHOTO_SRC = svgData(`
<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720" viewBox="0 0 1280 720">
  <defs>
    <linearGradient id="sky" x1="0" x2="0" y1="0" y2="1">
      <stop stop-color="#1b1440"/>
      <stop offset=".42" stop-color="#7b3f5e"/>
      <stop offset=".68" stop-color="#e0784a"/>
      <stop offset="1" stop-color="#f7c07a"/>
    </linearGradient>
    <radialGradient id="sun" cx=".5" cy=".5" r=".5">
      <stop stop-color="#fff3d4"/>
      <stop offset=".55" stop-color="#ffcf7a"/>
      <stop offset="1" stop-color="#ffcf7a" stop-opacity="0"/>
    </radialGradient>
    <linearGradient id="water" x1="0" x2="0" y1="0" y2="1">
      <stop stop-color="#c9764f"/>
      <stop offset=".4" stop-color="#5c3552"/>
      <stop offset="1" stop-color="#231a3a"/>
    </linearGradient>
    <linearGradient id="haze" x1="0" x2="0" y1="0" y2="1">
      <stop stop-color="#f7c07a" stop-opacity="0"/>
      <stop offset="1" stop-color="#f7c07a" stop-opacity=".26"/>
    </linearGradient>
  </defs>
  <rect width="1280" height="720" fill="url(#sky)"/>
  <circle cx="742" cy="452" r="196" fill="url(#sun)"/>
  <circle cx="742" cy="452" r="62" fill="#fff6e0"/>
  <path d="M0 372 L152 268 L268 336 L372 246 L470 330 L560 292 L640 356 L640 470 L0 470 Z" fill="#3a2b52" opacity=".92"/>
  <path d="M1280 356 L1150 262 L1044 330 L940 250 L846 322 L760 292 L688 356 L688 470 L1280 470 Z" fill="#3a2b52" opacity=".92"/>
  <path d="M0 470 L0 402 L118 330 L236 396 L360 316 L470 392 L604 322 L724 400 L860 320 L980 396 L1104 328 L1280 412 L1280 470 Z" fill="#241a38"/>
  <rect y="404" width="1280" height="66" fill="url(#haze)"/>
  <rect y="470" width="1280" height="250" fill="url(#water)"/>
  <ellipse cx="742" cy="484" rx="128" ry="11" fill="#ffe6b8" opacity=".4"/>
  <ellipse cx="736" cy="514" rx="104" ry="6" fill="#ffd79a" opacity=".3"/>
  <ellipse cx="756" cy="548" rx="132" ry="5" fill="#ffd79a" opacity=".22"/>
  <ellipse cx="724" cy="592" rx="96" ry="5" fill="#ffd79a" opacity=".16"/>
  <ellipse cx="768" cy="646" rx="150" ry="4" fill="#ffd79a" opacity=".11"/>
  <ellipse cx="712" cy="694" rx="112" ry="4" fill="#ffd79a" opacity=".08"/>
  <path d="M0 720 L0 604 C104 590 176 630 268 648 C352 664 402 700 448 720 Z" fill="#150f28"/>
  <path d="M1280 720 L1280 632 C1188 626 1120 664 1042 686 C990 700 954 712 928 720 Z" fill="#150f28"/>
</svg>`);

export const DEMO_MEDIA_ALT_SRC = svgData(`
<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720" viewBox="0 0 1280 720">
  <rect width="1280" height="720" fill="#070812"/>
  <path d="M0 520 C180 420 340 580 520 460 C720 326 850 390 1020 250 C1120 170 1210 150 1280 120 L1280 720 L0 720 Z" fill="#ec4899" opacity=".30"/>
  <rect x="730" y="100" width="350" height="440" rx="58" fill="#fdf2f8" opacity=".12"/>
  <circle cx="905" cy="292" r="118" fill="#f9a8d4" opacity=".80"/>
  <rect x="804" y="452" width="210" height="36" rx="18" fill="#fdf2f8" opacity=".70"/>
  <text x="110" y="210" font-family="Arial,sans-serif" font-size="70" font-weight="800" fill="#f8fafc">Creator cut</text>
  <text x="112" y="286" font-family="Arial,sans-serif" font-size="34" fill="#f9a8d4">Talking head, captions, and proof clips</text>
</svg>`);

/** `DEMO_MEDIA_ALT_SRC` without its baked copy — see `DEMO_MEDIA_PLAIN_SRC`. */
export const DEMO_MEDIA_ALT_PLAIN_SRC = svgData(`
<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720" viewBox="0 0 1280 720">
  <rect width="1280" height="720" fill="#070812"/>
  <path d="M0 520 C180 420 340 580 520 460 C720 326 850 390 1020 250 C1120 170 1210 150 1280 120 L1280 720 L0 720 Z" fill="#ec4899" opacity=".30"/>
  <rect x="730" y="100" width="350" height="440" rx="58" fill="#fdf2f8" opacity=".12"/>
  <circle cx="905" cy="292" r="118" fill="#f9a8d4" opacity=".80"/>
  <rect x="804" y="452" width="210" height="36" rx="18" fill="#fdf2f8" opacity=".70"/>
  <rect x="110" y="180" width="300" height="30" rx="15" fill="#f8fafc" opacity=".26"/>
  <rect x="112" y="256" width="200" height="20" rx="10" fill="#f9a8d4" opacity=".34"/>
</svg>`);

/**
 * Portrait speaker still.
 *
 * The other demo stills are 16:9 product cards with their own headline baked
 * in, which crop into nonsense inside a talking-head frame — this one is framed
 * the way a camera actually frames a person.
 *
 * It is deliberately a *portrait*, not an avatar glyph. The previous version
 * was a head-and-shoulders silhouette almost identical to the component's own
 * `PlaceholderSpeaker`, so a reader could not tell whether `mediaSrc` was
 * working at all — the one component whose subject is a person on camera looked
 * like a missing image.
 */
export const DEMO_SPEAKER_SRC = svgData(`
<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350" viewBox="0 0 1080 1350">
  <defs>
    <linearGradient id="room" x1="0" x2="1" y1="0" y2="1">
      <stop stop-color="#1b2330"/>
      <stop offset="1" stop-color="#070a10"/>
    </linearGradient>
    <radialGradient id="key" cx="0.3" cy="0.24" r="0.72">
      <stop stop-color="#2dd4bf" stop-opacity=".30"/>
      <stop offset="1" stop-color="#2dd4bf" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="rim" cx="0.86" cy="0.28" r="0.5">
      <stop stop-color="#f59e0b" stop-opacity=".26"/>
      <stop offset="1" stop-color="#f59e0b" stop-opacity="0"/>
    </radialGradient>
    <linearGradient id="skin" x1="0.15" x2="0.95" y1="0" y2="1">
      <stop stop-color="#cf9670"/>
      <stop offset="1" stop-color="#8d573a"/>
    </linearGradient>
    <linearGradient id="shirt" x1="0" x2="1" y1="0" y2="1">
      <stop stop-color="#2c4a68"/>
      <stop offset="1" stop-color="#14253a"/>
    </linearGradient>
  </defs>

  <rect width="1080" height="1350" fill="url(#room)"/>
  <rect width="1080" height="1350" fill="url(#key)"/>
  <rect width="1080" height="1350" fill="url(#rim)"/>

  <!-- Out-of-focus practicals behind the subject: depth, not decoration. -->
  <circle cx="146" cy="322" r="96" fill="#f59e0b" opacity=".10"/>
  <circle cx="916" cy="212" r="128" fill="#2dd4bf" opacity=".10"/>
  <circle cx="842" cy="452" r="58" fill="#f59e0b" opacity=".09"/>
  <rect x="72" y="620" width="150" height="470" rx="20" fill="#2dd4bf" opacity=".05"/>

  <!-- Shoulders -->
  <path d="M156 1350c0-224 132-338 384-338s384 114 384 338Z" fill="url(#shirt)"/>
  <path d="M466 1030l74 84 74-84" stroke="#0d1a27" stroke-width="18" stroke-linecap="round" fill="none"/>
  <path d="M540 1114v236" stroke="#0d1a27" stroke-width="12" stroke-linecap="round" opacity=".7"/>

  <!-- Neck -->
  <rect x="466" y="806" width="148" height="240" rx="70" fill="url(#skin)"/>
  <ellipse cx="540" cy="838" rx="120" ry="52" fill="#3d2517" opacity=".42"/>

  <!-- Head -->
  <ellipse cx="384" cy="700" rx="26" ry="42" fill="url(#skin)"/>
  <ellipse cx="696" cy="700" rx="26" ry="42" fill="url(#skin)"/>
  <ellipse cx="540" cy="686" rx="158" ry="192" fill="url(#skin)"/>

  <!-- Hair -->
  <path d="M540 448c-116 0-180 82-180 186 0 26 4 50 12 68 10-80 50-126 102-144 42-14 90-14 132 0 52 18 92 64 102 144 8-18 12-42 12-68 0-104-64-186-180-186Z" fill="#231a17"/>

  <!-- Brows, eyes, nose, mouth -->
  <path d="M446 646c20-16 52-16 70-6" stroke="#231a17" stroke-width="13" stroke-linecap="round" fill="none"/>
  <path d="M564 640c18-10 50-10 70 6" stroke="#231a17" stroke-width="13" stroke-linecap="round" fill="none"/>
  <ellipse cx="480" cy="694" rx="21" ry="12" fill="#111820"/>
  <ellipse cx="600" cy="694" rx="21" ry="12" fill="#111820"/>
  <circle cx="486" cy="690" r="5" fill="#f8fafc" opacity=".85"/>
  <circle cx="606" cy="690" r="5" fill="#f8fafc" opacity=".85"/>
  <path d="M540 706v44c0 10-8 16-19 18" stroke="#7d4b30" stroke-width="10" stroke-linecap="round" fill="none" opacity=".65"/>
  <ellipse cx="540" cy="806" rx="38" ry="19" fill="#5c2f26"/>
  <path d="M502 800c14-14 62-14 76 0" stroke="#6f3a2a" stroke-width="11" stroke-linecap="round" fill="none"/>

  <!-- Rim light down the camera-right edge -->
  <path d="M688 594c20 44 20 118-4 168" stroke="#f8fafc" stroke-width="11" opacity=".26" stroke-linecap="round" fill="none"/>
  <path d="M842 1108c-42-58-108-96-176-116" stroke="#f8fafc" stroke-width="9" opacity=".14" stroke-linecap="round" fill="none"/>
</svg>`);

export const DEMO_MEDIA_THIRD_SRC = svgData(`
<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720" viewBox="0 0 1280 720">
  <rect width="1280" height="720" fill="#101827"/>
  <rect x="120" y="92" width="1040" height="536" rx="46" fill="#f8fafc" opacity=".09"/>
  <rect x="170" y="160" width="294" height="360" rx="32" fill="#34d399" opacity=".74"/>
  <rect x="520" y="166" width="570" height="54" rx="27" fill="#f8fafc" opacity=".76"/>
  <rect x="520" y="260" width="470" height="34" rx="17" fill="#cbd5e1" opacity=".7"/>
  <rect x="520" y="326" width="520" height="34" rx="17" fill="#cbd5e1" opacity=".44"/>
  <rect x="520" y="448" width="260" height="72" rx="36" fill="#34d399"/>
  <text x="176" y="584" font-family="Arial,sans-serif" font-size="42" font-weight="800" fill="#f8fafc">Publish screen</text>
</svg>`);

/**
 * Portrait app capture. The 16:9 stills above are cropped to a sliver by
 * `object-fit: cover` inside a 1080x1920 composition, which turns their baked-in
 * headlines into unreadable letters — a vertical walkthrough needs a capture
 * that was framed vertically in the first place.
 *
 * Every control carries its real label. The earlier version was grey placeholder
 * bars end to end, so a walkthrough that spotlit its primary button spotlit a
 * blank pill: the whole media beat read as a loading state rather than a product.
 * Copy sits away from the lower band, which is where overlaying scenes put their
 * captions — see `DEMO_MEDIA_PLAIN_SRC`.
 */
export const DEMO_APP_PORTRAIT_SRC = svgData(`
<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920">
  <defs>
    <linearGradient id="app" x1="0" x2="1" y1="0" y2="1">
      <stop stop-color="#111827"/>
      <stop offset="1" stop-color="#1a1510"/>
    </linearGradient>
  </defs>
  <rect width="1080" height="1920" fill="url(#app)"/>
  <circle cx="880" cy="250" r="260" fill="${DEMO_PALETTE.phosphor}" opacity=".14"/>
  <text x="96" y="182" font-family="Arial,sans-serif" font-size="38" font-weight="600" fill="#f8fafc" opacity=".55">Projects / Launch clip</text>
  <text x="96" y="290" font-family="Arial,sans-serif" font-size="76" font-weight="700" fill="#f8fafc">Launch run</text>
  <rect x="96" y="400" width="888" height="300" rx="44" fill="#f8fafc" opacity=".10"/>
  <text x="152" y="496" font-family="Arial,sans-serif" font-size="44" font-weight="700" fill="#f8fafc">social-clip.tsx</text>
  <text x="152" y="558" font-family="Arial,sans-serif" font-size="34" font-weight="600" fill="${DEMO_PALETTE.phosphor}">1080 x 1920 &#183; 30 fps &#183; h264</text>
  <rect x="152" y="596" width="640" height="52" rx="26" fill="#020617" opacity=".42"/>
  <text x="184" y="633" font-family="Arial,sans-serif" font-size="30" font-weight="600" fill="#f8fafc" opacity=".8">All 5 scenes wired</text>
  <rect x="96" y="748" width="430" height="270" rx="40" fill="#f8fafc" opacity=".08"/>
  <rect x="554" y="748" width="430" height="270" rx="40" fill="#f8fafc" opacity=".08"/>
  <text x="152" y="852" font-family="Arial,sans-serif" font-size="32" font-weight="600" fill="#f8fafc" opacity=".55">Duration</text>
  <text x="152" y="948" font-family="Arial,sans-serif" font-size="62" font-weight="700" fill="#f8fafc">12.0s</text>
  <text x="610" y="852" font-family="Arial,sans-serif" font-size="32" font-weight="600" fill="#f8fafc" opacity=".55">Frames</text>
  <text x="610" y="948" font-family="Arial,sans-serif" font-size="62" font-weight="700" fill="#f8fafc">360</text>
  <rect x="96" y="1080" width="888" height="120" rx="60" fill="${DEMO_PALETTE.amber}" opacity=".92"/>
  <text x="540" y="1158" text-anchor="middle" font-family="Arial,sans-serif" font-size="46" font-weight="700" fill="#1a1510">Render</text>
  <rect x="96" y="1560" width="888" height="220" rx="44" fill="#f8fafc" opacity=".06"/>
  <text x="152" y="1648" font-family="Arial,sans-serif" font-size="34" font-weight="600" fill="#f8fafc" opacity=".62">Last run 4.2s on the free tier</text>
  <text x="152" y="1716" font-family="Arial,sans-serif" font-size="34" font-weight="600" fill="#f8fafc" opacity=".38">Queue empty</text>
</svg>`);

/** RemotionUI logo mark — matches apps/web/public/logo.svg */
export const DEMO_LOGO_SRC = svgData(BRAND_MARK_SVG);

export const DEMO_SOCIAL_CLIP_CAPTIONS: Caption[] = [
  { text: " Install", startMs: 0, endMs: 360, timestampMs: 0, confidence: 1 },
  { text: " components", startMs: 360, endMs: 780, timestampMs: 360, confidence: 1 },
  { text: " as", startMs: 780, endMs: 980, timestampMs: 780, confidence: 1 },
  { text: " source", startMs: 980, endMs: 1800, timestampMs: 980, confidence: 1 },
];

/**
 * Real subtitle file for the `srt-caption-track` demo.
 *
 * A `staticFile()` URL rather than an inline string on purpose: the preview
 * then exercises the fetch-behind-`delayRender()` path that a real transcript
 * takes, so a broken loader fails the audit render instead of passing it.
 */
export const DEMO_SRT_SRC = staticFile("fixtures/demo-captions.srt");

export const DEMO_CAPTIONS: Caption[] = [
  { text: " Clip", startMs: 0, endMs: 400, timestampMs: 0, confidence: 1 },
  { text: " the", startMs: 400, endMs: 600, timestampMs: 400, confidence: 1 },
  {
    text: " sharpest",
    startMs: 600,
    endMs: 1200,
    timestampMs: 600,
    confidence: 1,
  },
  {
    text: " moment",
    startMs: 1200,
    endMs: 2000,
    timestampMs: 1200,
    confidence: 1,
  },
];

/** Stylized “R” mark for logo-reveal / path-draw demos */
export const DEMO_LOGO_PATH =
  "M 52 28 L 52 172 L 96 172 Q 138 172 138 128 Q 138 96 108 88 L 144 28 L 112 28 L 92 78 L 84 78 L 84 28 Z";

export const DEMO_BAR_DATA = [
  { label: "Shorts", value: 124000, delta: "+32%" },
  { label: "Podcast", value: 82000, delta: "+11%" },
  { label: "Docs", value: 64000, delta: "+4%" },
  { label: "Launch", value: 48000, delta: "-6%" },
];

export const DEMO_METRICS = [
  {
    label: "Views",
    value: 124000,
    delta: "+18%",
    trend: [62, 71, 68, 84, 96, 112, 124],
  },
  {
    label: "Watch time",
    value: 48,
    suffix: "min",
    delta: "+6%",
    trend: [39, 41, 40, 43, 45, 44, 48],
  },
  {
    label: "Shares",
    value: 3200,
    delta: "-4%",
    trend: [3.6, 3.5, 3.7, 3.4, 3.3, 3.35, 3.2],
  },
];

export const DEMO_TIMELINE_STEPS = [
  { title: "Hook", description: "Lead with the sharpest insight." },
  { title: "Proof", description: "Show the chart and metrics." },
  { title: "CTA", description: "Close with one clear next step." },
];

export const DEMO_LINE_POINTS = [
  { x: 0, y: 12000, label: "Jan" },
  { x: 1, y: 18400, label: "Feb" },
  { x: 2, y: 16200, label: "Mar" },
  { x: 3, y: 28600, label: "Apr" },
  { x: 4, y: 44100, label: "May" },
  { x: 5, y: 52800, label: "Jun" },
];
