"""
land-dots.py — bake the globe's land dot matrix into a TypeScript module.

Samples a Fibonacci sphere and keeps the points that fall on land according to
public/geo/land-110m.json (Natural Earth 1:110m, public domain). The result is
committed as src/panels/edge/land-dots.ts so the render never parses GeoJSON.

    python3 showcase/supabase-demo/scripts/land-dots.py   # run from apps/web
"""

import json
import math
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[3]
LAND = ROOT / "public" / "geo" / "land-110m.json"
OUT = Path(__file__).resolve().parents[1] / "src" / "panels" / "edge" / "land-dots.ts"
SAMPLES = 5200


def rings(geojson):
    for feature in geojson["features"]:
        geometry = feature["geometry"]
        polygons = geometry["coordinates"]
        if geometry["type"] == "Polygon":
            polygons = [polygons]
        for polygon in polygons:
            yield np.array(polygon[0], dtype=float)


def inside(ring, lon, lat):
    x, y = ring[:, 0], ring[:, 1]
    x2, y2 = np.roll(x, -1), np.roll(y, -1)
    hit = np.zeros(lon.shape, dtype=bool)
    for a, b, c, d in zip(x, y, x2, y2):
        crosses = (b > lat) != (d > lat)
        with np.errstate(divide="ignore", invalid="ignore"):
            at = (c - a) * (lat - b) / (d - b) + a
        hit ^= crosses & (lon < at)
    return hit


def main():
    geojson = json.loads(LAND.read_text())
    golden = math.pi * (3 - math.sqrt(5))
    i = np.arange(SAMPLES)
    y = 1 - (i / (SAMPLES - 1)) * 2
    theta = golden * i
    lat = np.degrees(np.arcsin(y))
    lon = (np.degrees(theta) + 180) % 360 - 180

    land = np.zeros(SAMPLES, dtype=bool)
    for ring in rings(geojson):
        land |= inside(ring, lon, lat)

    points = [(round(float(a), 1), round(float(o), 1)) for a, o in zip(lat[land], lon[land])]
    body = ",".join(f"[{a},{o}]" for a, o in points)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/land-dots.py from Natural Earth 1:110m land (public domain).\n"
        "// [latitude, longitude] of Fibonacci-sphere samples that sit on land.\n"
        f"export const LAND_DOTS: ReadonlyArray<readonly [number, number]> = [{body}];\n"
    )
    print(f"{len(points)} land dots -> {OUT}")


if __name__ == "__main__":
    main()
