import { NamePool, toCamelCase, toKebabCase, toPascalCase } from "./names.js";
import type { ParsedAnimation, ParsedComp, ParsedLayer } from "./parse.js";
import { Call, commentSafe, formatNumber, print, Ref } from "./printer.js";
import type { ImportIssue } from "./properties.js";

/**
 * The importable model → TSX. One file per composition: the main one in
 * `index.tsx`, each precomp beside it. Layers are data consts built with the
 * `ae-import` constructors, each drawn by a small named component, and the
 * composition lists those components bottom-to-top.
 */

export type GeneratedFile = { path: string; content: string };

export type CompositionInfo = {
  id: string;
  component: string;
  durationInFrames: number;
  fps: number;
  width: number;
  height: number;
};

export type CodegenOptions = {
  /** Component and composition id, PascalCase. */
  name: string;
  /** Shown in the header, e.g. the input file's base name. */
  sourceLabel: string;
  /** Module path the runtime is imported from. */
  runtimeImport: string;
  /** Issues to list in the header when generating past them. */
  issues?: readonly ImportIssue[];
};

const LAYER_CONSTRUCTOR: Record<ParsedLayer["kind"], string> = {
  shape: "shapeLayer",
  solid: "solidLayer",
  null: "nullLayer",
  precomp: "precompLayer",
};

const RUNTIME_EXPORTS = [
  "AeComposition",
  "AeLayer",
  "shapeLayer",
  "solidLayer",
  "nullLayer",
  "precompLayer",
  "spatial",
  "separate",
  "combine",
  "group",
  "path",
  "rect",
  "ellipse",
  "star",
  "polygon",
  "fill",
  "stroke",
  "gradientFill",
  "gradientStroke",
  "trim",
  "repeater",
  "offsetPathItem",
  "zigZag",
  "puckerBloat",
];

type CompNames = { component: string; file: string };

function collectCalls(value: unknown, into: Set<string>): void {
  if (value instanceof Call) {
    into.add(value.fn);
    value.args.forEach((arg) => collectCalls(arg, into));
  } else if (Array.isArray(value)) value.forEach((v) => collectCalls(v, into));
  else if (value && typeof value === "object" && !(value instanceof Ref)) {
    Object.values(value as Record<string, unknown>).forEach((v) => collectCalls(v, into));
  }
}

/** Parents before children, otherwise Lottie order. */
function declarationOrder(layers: readonly ParsedLayer[]): ParsedLayer[] {
  const byIndex = new Map(layers.map((l) => [l.index, l]));
  const out: ParsedLayer[] = [];
  const placed = new Set<number>();
  const place = (layer: ParsedLayer) => {
    if (placed.has(layer.index)) return;
    const parent = layer.parent === undefined ? undefined : byIndex.get(layer.parent);
    if (parent) place(parent);
    placed.add(layer.index);
    out.push(layer);
  };
  layers.forEach(place);
  return out;
}

const frames = (layer: ParsedLayer) =>
  `frames ${formatNumber(Number(layer.spec.inPoint), 2)}–${formatNumber(Number(layer.spec.outPoint), 2)}`;

function header(opts: CodegenOptions, anim: ParsedAnimation, scope: string): string[] {
  const lines = [
    "/**",
    ` * ${commentSafe(scope)} — generated by \`remotion-ui import-ae\` from ${commentSafe(opts.sourceLabel)}` +
      (anim.version ? ` (Bodymovin ${commentSafe(anim.version)}).` : "."),
    ` * ${anim.width}×${anim.height} at ${formatNumber(anim.fps, 3)} fps, ${anim.durationInFrames} frames.`,
    " *",
    " * Plain data on top of `ae-motion`: keyframe frames are this composition's",
    " * frames, speed is units per second, scale is a factor and opacity is 0–1.",
    " * Edit a key, a colour or a layer's inPoint/outPoint/startTime and re-render.",
  ];
  const unsupported = (opts.issues ?? []).filter((i) => i.level === "unsupported");
  if (unsupported.length > 0) {
    lines.push(" *", " * Not imported (generated with --skip-unsupported):");
    for (const issue of unsupported) {
      lines.push(` * - ${commentSafe(`${issue.feature}: ${issue.where} — ${issue.detail}`)}`);
    }
  }
  lines.push(" */");
  return lines;
}

function renderComp(
  comp: ParsedComp,
  kind: "main" | "precomp",
  compNames: Map<string, CompNames>,
  anim: ParsedAnimation,
  opts: CodegenOptions,
  pool: NamePool,
): { body: string[]; calls: Set<string>; precompImports: Set<string> } {
  const calls = new Set<string>(["AeLayer"]);
  const precompImports = new Set<string>();
  const consts = new Map<number, string>();
  const components = new Map<number, string>();
  const body: string[] = [];

  const ordered = declarationOrder(comp.layers);
  for (const layer of ordered) {
    consts.set(layer.index, pool.claim(`${toCamelCase(layer.name)}Layer`));
    if (layer.kind !== "null") components.set(layer.index, pool.claim(toPascalCase(layer.name)));
  }

  for (const layer of ordered) {
    const constructor = LAYER_CONSTRUCTOR[layer.kind];
    calls.add(constructor);
    const { name, ...rest } = layer.spec;
    const spec = {
      name,
      ...(layer.parent !== undefined ? { parent: new Ref(consts.get(layer.parent)!) } : {}),
      ...rest,
    };
    collectCalls(spec, calls);
    const typeLabel = layer.kind === "precomp" ? `precomp layer (${compNames.get(layer.precomp!)?.component})` : `${layer.kind} layer`;
    const note = layer.note ? ` ${layer.note}.` : "";
    body.push(
      "",
      `/** ${commentSafe(`"${layer.name}" — ${typeLabel}, ${frames(layer)}.${note}`)} */`,
      `const ${consts.get(layer.index)} = ${print(new Call(constructor, [spec]))};`,
    );
    const component = components.get(layer.index);
    if (!component) continue;
    if (layer.kind === "precomp") {
      const target = compNames.get(layer.precomp!)!;
      precompImports.add(layer.precomp!);
      body.push(
        "",
        `export const ${component} = () => (`,
        `  <AeLayer layer={${consts.get(layer.index)}}>`,
        `    <${target.component} />`,
        "  </AeLayer>",
        ");",
      );
    } else {
      body.push("", `export const ${component} = () => <AeLayer layer={${consts.get(layer.index)}} />;`);
    }
  }

  // Bottom of the AE timeline first: in SVG, later children draw on top.
  const stack = [...comp.layers].reverse().flatMap((l) => {
    const c = components.get(l.index);
    return c ? [`    <${c} />`] : [];
  });
  const self = compNames.get(comp.id)!.component;
  body.push("");
  if (kind === "main") {
    calls.add("AeComposition");
    const startFrame = anim.inPoint !== 0 ? ` startFrame={${formatNumber(anim.inPoint)}}` : "";
    body.push(
      `/** The composition. Layers are listed bottom of the AE timeline first — later ones draw on top. */`,
      `export const ${self} = () => (`,
      `  <AeComposition width={${formatNumber(comp.width)}} height={${formatNumber(comp.height)}} fps={${formatNumber(anim.fps)}}${startFrame}>`,
      ...stack,
      "  </AeComposition>",
      ");",
    );
  } else {
    body.push(
      `/** "${commentSafe(comp.name)}" precomp (${formatNumber(comp.width)}×${formatNumber(comp.height)}), bottom layer first. */`,
      `export const ${self} = () => (`,
      "  <>",
      ...stack,
      "  </>",
      ");",
    );
  }
  return { body, calls, precompImports };
}

function importLine(names: Iterable<string>, from: string): string {
  const sorted = RUNTIME_EXPORTS.filter((n) => [...names].includes(n));
  const inline = `import { ${sorted.join(", ")} } from ${JSON.stringify(from)};`;
  if (inline.length <= 96) return inline;
  return `import {\n${sorted.map((n) => `  ${n},`).join("\n")}\n} from ${JSON.stringify(from)};`;
}

/** Generate the files for a parsed animation. Paths are relative to the output dir. */
export function generate(anim: ParsedAnimation, opts: CodegenOptions): { files: GeneratedFile[]; composition: CompositionInfo } {
  const pool = new NamePool([...RUNTIME_EXPORTS, opts.name]);
  const compNames = new Map<string, CompNames>();
  compNames.set("main", { component: opts.name, file: "index.tsx" });
  const files = new Set(["index"]);
  for (const precomp of anim.precomps) {
    let file = toKebabCase(precomp.name, "precomp");
    for (let n = 2; files.has(file); n += 1) file = `${toKebabCase(precomp.name, "precomp")}-${n}`;
    files.add(file);
    compNames.set(precomp.id, { component: pool.claim(`${toPascalCase(precomp.name, "Comp")}Precomp`), file: `${file}.tsx` });
  }

  const out: GeneratedFile[] = [];
  const scopes: Array<[ParsedComp, "main" | "precomp"]> = [[anim.main, "main"], ...anim.precomps.map((p): [ParsedComp, "precomp"] => [p, "precomp"])];
  for (const [comp, kind] of scopes) {
    const { body, calls, precompImports } = renderComp(comp, kind, compNames, anim, opts, pool);
    const names = compNames.get(comp.id)!;
    const imports = [importLine(calls, opts.runtimeImport)];
    for (const id of precompImports) {
      const target = compNames.get(id)!;
      imports.push(`import { ${target.component} } from "./${target.file.replace(/\.tsx$/, "")}";`);
    }
    const scope = kind === "main" ? `${opts.name}` : `${comp.name} precomp`;
    const lines = [...header(opts, anim, scope), ...imports.sort(), ...body];
    if (kind === "main") {
      lines.push(
        "",
        "/** Register with `<Composition {...config} />`; `remotion-ui import-ae` adds it to Root.tsx for you. */",
        `export const ${toCamelCase(opts.name, "animation")}Composition = ${print({
          id: opts.name,
          component: new Ref(opts.name),
          durationInFrames: anim.durationInFrames,
          fps: anim.fps,
          width: anim.width,
          height: anim.height,
        })};`,
      );
    }
    out.push({ path: names.file, content: `${lines.join("\n")}\n` });
  }

  return {
    files: out,
    composition: {
      id: opts.name,
      component: opts.name,
      durationInFrames: anim.durationInFrames,
      fps: anim.fps,
      width: anim.width,
      height: anim.height,
    },
  };
}
